In [16]:
import numpy as np


In [17]:
# 1.  Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and print 
#  The first row 
# The last column 
# The diagonal elements 

print("Ques 1")
mat1 = np.arange(1, 26).reshape(5, 5)

print("Matrix:", mat1)
print("First Row:", mat1[0])
print("Last Column:", mat1[:, -1])
print("Diagonal Elements:", np.diag(mat1))


Ques 1
Matrix: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row: [1 2 3 4 5]
Last Column: [ 5 10 15 20 25]
Diagonal Elements: [ 1  7 13 19 25]


In [18]:
#  2.  Create two 3 × 3 matrices and perform matrix addition, subtraction, 
# and matrix multiplication.

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", np.dot(A, B))

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [19]:
# 3. Create a NumPy array of numbers from 1 to 100 and print all numbers 
# divisible by 3 using Boolean indexing.

arr = np.arange(1, 101)
print(arr[arr % 3 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [20]:
# 4.
mat4 = np.arange(1, 17).reshape(4, 4)
print("Original Matrix:", mat4)

mat4[mat4 % 2 == 0] = 0
print("Modified Matrix:", mat4)

Original Matrix: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified Matrix: [[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [21]:
# 5.

mat5 = np.random.randint(1, 100, (5, 5))
print("Matrix:", mat5)

print("Maximum:", np.max(mat5))
print("Minimum:", np.min(mat5))
print("Mean:", np.mean(mat5))
print("Median:", np.median(mat5))


Matrix: [[48 60 39 45  2]
 [58 87 96 90 14]
 [67 90 58 76 82]
 [77 51 12 16 63]
 [87 91  3  9 21]]
Maximum: 96
Minimum: 2
Mean: 53.68
Median: 58.0


In [22]:
# 6.

print("\n6. Sorting Random Array")

arr6 = np.random.randint(1, 100, 20)
print("Original Array:", arr6)

print("Ascending Order:", np.sort(arr6))
print("Descending Order:", np.sort(arr6)[::-1])





6. Sorting Random Array
Original Array: [18  5 60 42 59 45 13  5 36 19 90 56  7 83 16 40 87 87 68 70]
Ascending Order: [ 5  5  7 13 16 18 19 36 40 42 45 56 59 60 68 70 83 87 87 90]
Descending Order: [90 87 87 83 70 68 60 59 56 45 42 40 36 19 18 16 13  7  5  5]


In [23]:
# 7.

print("\n7. Triangular Matrix Operations")

mat7 = np.arange(1, 37).reshape(6, 6)
print("Matrix:\n", mat7)

print("Main Diagonal:", np.diag(mat7))
print("Upper Triangular:\n", np.triu(mat7))
print("Lower Triangular:\n", np.tril(mat7))


7. Triangular Matrix Operations
Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Main Diagonal: [ 1  8 15 22 29 36]
Upper Triangular:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Lower Triangular:
 [[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


In [24]:
# 8.

print("\n8. Reshaping Array")

arr8 = np.arange(1, 21)

print("4×5 Matrix:\n", arr8.reshape(4, 5))
print("2×10 Matrix:\n", arr8.reshape(2, 10))
print("5×4 Matrix:\n", arr8.reshape(5, 4))


8. Reshaping Array
4×5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
2×10 Matrix:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
5×4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [25]:
# 9.

print("\n9. Row and Column Sums")

mat9 = np.arange(1, 26).reshape(5, 5)
print("Matrix:\n", mat9)

print("Row Sums:", np.sum(mat9, axis=1))
print("Column Sums:", np.sum(mat9, axis=0))



9. Row and Column Sums
Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Row Sums: [ 15  40  65  90 115]
Column Sums: [55 60 65 70 75]


In [26]:
# 10.

print("\n10. Common Elements")

arr10_a = np.array([1, 2, 3, 4, 5, 6])
arr10_b = np.array([4, 5, 6, 7, 8, 9])

print("Common Elements:", np.intersect1d(arr10_a, arr10_b))


10. Common Elements
Common Elements: [4 5 6]


In [27]:
# 11.

print("\n11. Position of Largest Element")

mat11 = np.random.randint(1, 100, (5, 5))
print("Matrix:\n", mat11)

max_pos = np.unravel_index(np.argmax(mat11), mat11.shape)

print("Largest Element:", np.max(mat11))
print("Position (row, column):", max_pos)


11. Position of Largest Element
Matrix:
 [[67 98 26 45 18]
 [26 59 29 28 23]
 [15 78 87 24 90]
 [90 85 65 56 27]
 [51 60 34 80 68]]
Largest Element: 98
Position (row, column): (np.int64(0), np.int64(1))


In [28]:
# 12.

print("\n12. Student Marks Analysis")

students = np.array([
    78, 85, 92, 67, 88,
    95, 73, 81, 69, 90
])

print("Marks:", students)

highest = np.max(students)
lowest = np.min(students)
average = np.mean(students)

print("Highest Marks:", highest)
print("Lowest Marks:", lowest)
print("Average Marks:", average)

above_average = students[students > average]
print("Students Scoring Above Average:", above_average)


12. Student Marks Analysis
Marks: [78 85 92 67 88 95 73 81 69 90]
Highest Marks: 95
Lowest Marks: 67
Average Marks: 81.8
Students Scoring Above Average: [85 92 88 95 90]
